import json
import math
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd
from mlxtend.frequent_patterns import association_rules, fpgrowth

# ─────────────────────────────────────────────────────────────────────────────
# PokéML Recommender — ML Engine
# No database required. Reads transaction data from data/transactions.json
# (generated by generate_data.py), runs FP-Growth association rule mining
# across three iteration windows, and writes results to public/analysis-results.json
# for the React frontend to display.
# ─────────────────────────────────────────────────────────────────────────────

DATA_FILE = Path(__file__).resolve().parent / "data" / "transactions.json"


# ─── DATA LOADING ─────────────────────────────────────────────────────────────

def load_transactions() -> pd.DataFrame:
    """Load all transaction rows from the local JSON file into a DataFrame."""
    if not DATA_FILE.exists():
        raise FileNotFoundError(
            f"Transaction data not found at {DATA_FILE}\n"
            "Run generate_data.py first to create the data file."
        )
    with open(DATA_FILE, encoding="utf-8") as f:
        rows = json.load(f)
    return pd.DataFrame(rows)


def get_max_transaction_id(df: pd.DataFrame) -> int:
    """Return the highest transaction_id in the dataset."""
    if df.empty:
        return 0
    return int(df["transaction_id"].max())


def filter_transactions(df: pd.DataFrame, min_id: int, max_id: int) -> pd.DataFrame:
    """Return only the rows whose transaction_id falls within [min_id, max_id]."""
    return df[(df["transaction_id"] >= min_id) & (df["transaction_id"] <= max_id)].copy()


def clean_transactions(df: pd.DataFrame) -> pd.DataFrame:
    """
    Clean and validate transaction rows before mining.

    Steps:
      1. Drop rows with null transaction_id or item_name (missing values)
      2. Strip leading/trailing whitespace from item_name strings
      3. Drop exact duplicate rows (same transaction_id + item_name pair)
      4. Ensure transaction_id is integer typed
      5. Reset index to a clean contiguous range

    Logs a summary of how many rows were removed at each stage.
    """
    original_count = len(df)

    # 1. Drop nulls
    df = df.dropna(subset=["transaction_id", "item_name"])
    after_nulls = len(df)

    # 2. Normalise item_name whitespace
    df["item_name"] = df["item_name"].str.strip()

    # 3. Drop exact duplicate rows (same TX buying same item twice)
    df = df.drop_duplicates(subset=["transaction_id", "item_name"])
    after_dupes = len(df)

    # 4. Ensure correct types
    df["transaction_id"] = df["transaction_id"].astype(int)

    # 5. Clean index
    df = df.reset_index(drop=True)

    nulls_removed = original_count - after_nulls
    dupes_removed = after_nulls - after_dupes
    print(
        f"  [Clean] {original_count} rows in "
        f"| nulls removed: {nulls_removed} "
        f"| duplicates removed: {dupes_removed} "
        f"| {len(df)} rows out"
    )

    return df


# ─── ITERATION RANGES ─────────────────────────────────────────────────────────

def build_iteration_ranges(max_transaction_id: int) -> list[tuple[str, int, int]]:
    """
    Build three cumulative analysis windows covering 25%, 50%, and 100%
    of the total transaction range. Windows always start from ID 1.
    """
    if max_transaction_id <= 0:
        return [
            ("Iteration 1: Early Launch Phase", 1, 500),
            ("Iteration 2: Mid-Season Update",  1, 1000),
            ("Iteration 3: Full Holiday Trend", 1, 2000),
        ]

    first_cutoff  = max(1, round(max_transaction_id * 0.25))
    second_cutoff = max(first_cutoff, round(max_transaction_id * 0.50))
    full_cutoff   = max(second_cutoff, max_transaction_id)

    return [
        ("Iteration 1: Early Launch Phase", 1, first_cutoff),
        ("Iteration 2: Mid-Season Update",  1, second_cutoff),
        ("Iteration 3: Full Holiday Trend", 1, full_cutoff),
    ]


# ─── RULE UTILITIES ───────────────────────────────────────────────────────────

def to_rule_signature(
    antecedents: frozenset[str] | set[str] | list[str],
    consequents: frozenset[str] | set[str] | list[str],
) -> str:
    """Create a deterministic directional string for a rule: 'A|B=>C'."""
    left  = "|".join(sorted(str(item) for item in antecedents))
    right = "|".join(sorted(str(item) for item in consequents))
    return f"{left}=>{right}"


def to_symmetric_signature(
    antecedents: frozenset[str] | set[str] | list[str],
    consequents: frozenset[str] | set[str] | list[str],
) -> str:
    """
    Create a direction-agnostic signature so that A=>B and B=>A
    produce the same string — used to detect and remove mirror rules.
    """
    left  = "|".join(sorted(str(item) for item in antecedents))
    right = "|".join(sorted(str(item) for item in consequents))
    return " <-> ".join(sorted([left, right]))


def is_collector_theme_rule(
    antecedents: frozenset[str] | set[str] | list[str],
    consequents: frozenset[str] | set[str] | list[str],
) -> bool:
    """
    Returns True if any item in the rule involves TCG/collector merchandise.
    These rules receive a soft +0.02 ranking boost to promote higher-margin items.
    """
    bundle_items = [str(item).lower() for item in list(antecedents) + list(consequents)]
    return any(
        ("card" in item) or ("graded" in item) or ("elite" in item) or ("booster" in item)
        for item in bundle_items
    )


def first_top_rule_signature(result: dict | None) -> str | None:
    """Extract the rule signature of the #1 ranked rule from an iteration result."""
    if not result:
        return None
    top_rules = result.get("topRules") or []
    if not top_rules:
        return None
    top_rule = top_rules[0]
    return to_rule_signature(
        top_rule.get("antecedentItems", []),
        top_rule.get("consequentItems", []),
    )


# ─── CORE ANALYSIS ────────────────────────────────────────────────────────────

def analyze_iteration(
    all_data: pd.DataFrame,
    iteration_name: str,
    min_id: int,
    max_id: int,
) -> dict:
    """
    Run the full FP-Growth pipeline on one iteration window.

    Steps:
      1.  Filter the full dataset to the transaction ID window
      2.  Clean rows: drop nulls, strip whitespace, remove duplicates
      3.  Pivot to a boolean basket matrix
      4.  Auto-scale the minimum support threshold by dataset size
      5.  Run FP-Growth to find frequent itemsets
      6.  Derive association rules (lift >= 1.0 only)
      7.  Score each rule: 0.4*Support + 0.4*Confidence + 0.2*Lift
      8.  Deduplicate mirror rules (keep stronger direction)
      9.  Apply soft collector theme bias (+0.02 ranking score)
      10. Select top 3 rules by ranking score
      11. Run stability check at 2x support threshold
      12. Build and return the result payload
    """
    print("\n" + "=" * 60)
    print(f"RUNNING: {iteration_name}")
    print("=" * 60)

    # ── Step 1: Filter to this iteration's window ──────────────────
    df = filter_transactions(all_data, min_id, max_id)

    if df.empty:
        print("No data found for this range.")
        return {
            "name": iteration_name,
            "range": {"min_id": min_id, "max_id": max_id},
            "transactionCount": 0,
            "rawRowCount": 0,
            "autoSupport": 0.0,
            "stabilitySupport": 0.0,
            "topRules": [],
        }

    # ── Step 2: Clean — drop nulls, whitespace, duplicates ─────────
    df = clean_transactions(df)

    # ── Step 3: Build boolean basket matrix ────────────────────────
    basket_counts = (
        df.groupby(["transaction_id", "item_name"])["item_name"]
        .count()
        .unstack()
        .fillna(0)
    )
    basket = basket_counts.gt(0)

    total_transactions = len(basket)
    raw_row_count      = len(df)

    # ── Step 3: Auto-scale minimum support threshold ───────────────
    if total_transactions <= 500:
        min_support = 0.04   # Small dataset — lower bar needed
    elif total_transactions <= 1000:
        min_support = 0.02
    else:
        min_support = 0.01   # Large dataset — tighter filter

    print(
        f"[PokéML Recommender] Transactions: {total_transactions} | "
        f"Auto-Support: {min_support}"
    )

    # ── Step 4: Run FP-Growth ──────────────────────────────────────
    frequent_itemsets = fpgrowth(basket, min_support=min_support, use_colnames=True)

    if frequent_itemsets.empty:
        print("No frequent itemsets found.")
        return {
            "name": iteration_name,
            "range": {"min_id": min_id, "max_id": max_id},
            "transactionCount": int(total_transactions),
            "rawRowCount": int(raw_row_count),
            "autoSupport": float(min_support),
            "stabilitySupport": float(min(min_support * 2, 1.0)),
            "topRules": [],
        }

    # ── Step 5: Derive association rules (lift >= 1.0 only) ────────
    rules = association_rules(
        frequent_itemsets,
        num_itemsets=total_transactions,
        metric="lift",
        min_threshold=1.0,
    )

    if rules.empty:
        print("No association rules found.")
        return {
            "name": iteration_name,
            "range": {"min_id": min_id, "max_id": max_id},
            "transactionCount": int(total_transactions),
            "rawRowCount": int(raw_row_count),
            "autoSupport": float(min_support),
            "stabilitySupport": float(min(min_support * 2, 1.0)),
            "topRules": [],
        }

    # ── Step 6: Composite weighted score ──────────────────────────
    rules["score"] = (
        (rules["support"]    * 0.4)
        + (rules["confidence"] * 0.4)
        + (rules["lift"]       * 0.2)
    )

    # ── Step 7: Deduplicate mirror rules ──────────────────────────
    rules["symmetricSignature"] = rules.apply(
        lambda row: to_symmetric_signature(row["antecedents"], row["consequents"]),
        axis=1,
    )
    rules = (
        rules.sort_values(["confidence", "support", "lift", "score"], ascending=False)
        .drop_duplicates(subset=["symmetricSignature"], keep="first")
        .reset_index(drop=True)
    )

    # ── Step 8: Collector theme bias ──────────────────────────────
    rules["collectorThemeEligible"] = rules.apply(
        lambda row: is_collector_theme_rule(row["antecedents"], row["consequents"]),
        axis=1,
    )
    # +0.02 nudge for TCG rules — does NOT affect the displayed score metric
    rules["rankingScore"] = rules["score"] + (rules["collectorThemeEligible"].astype(float) * 0.02)

    # ── Step 9: Select top 3 rules ────────────────────────────────
    top_rules = (
        rules.sort_values(
            ["rankingScore", "confidence", "support", "lift"],
            ascending=[False, False, False, False],
        )
        .head(3)
        .reset_index(drop=True)
    )

    # ── Step 10: Stability check at 2x support ────────────────────
    stability_support = min(min_support * 2, 1.0)
    stable_rule_signatures: set[str] = set()

    stable_itemsets = fpgrowth(basket, min_support=stability_support, use_colnames=True)
    if not stable_itemsets.empty:
        stable_rules = association_rules(
            stable_itemsets,
            num_itemsets=total_transactions,
            metric="lift",
            min_threshold=1.0,
        )
        if not stable_rules.empty:
            stable_rule_signatures = {
                to_rule_signature(row["antecedents"], row["consequents"])
                for _, row in stable_rules.iterrows()
            }

    # ── Step 11: Build result payload ─────────────────────────────
    print("\n--- HOMEPAGE & CART RECOMMENDATIONS ---")

    top_rule_payload = []
    for rank, row in top_rules.iterrows():
        antecedent_items = sorted(list(row["antecedents"]))
        consequent_items = sorted(list(row["consequents"]))
        antecedent       = ", ".join(antecedent_items)
        consequent       = ", ".join(consequent_items)
        conviction       = row.get("conviction", float("nan"))
        lift_value       = float(row["lift"])
        promo_discount   = 20 if lift_value > 1.5 else 10
        consequent_prefix = "".join(ch for ch in consequent.upper() if ch.isalnum())[:4]
        promo_code        = f"POKE{consequent_prefix}{int(round(lift_value * 100))}"
        weighted_score    = float(row["score"])
        signature         = to_rule_signature(antecedent_items, consequent_items)
        highly_stable     = signature in stable_rule_signatures

        print(f"\nFREQUENTLY BOUGHT TOGETHER: '{antecedent}' + '{consequent}'")
        print(
            f"  Homepage Ranking : Rank {rank + 1} "
            f"(Score = 0.4*Supp + 0.4*Conf + 0.2*Lift = {weighted_score:.3f})"
        )
        print(
            f"  Cart Suggestion  : When user adds '{antecedent}' → suggest '{consequent}'"
        )
        print(
            f"  Promo Generator  : CODE={promo_code} | Discount={promo_discount}% "
            f"(Lift={lift_value:.2f})"
        )
        print(
            f"  Metrics          : "
            f"Supp={row['support']:.3f} | "
            f"Conf={row['confidence']:.3f} | "
            f"Lift={lift_value:.3f} | "
            f"Lev={row['leverage']:.3f} | "
            f"Conv={conviction:.3f}"
        )
        if highly_stable:
            print("  Stability        : HIGHLY STABLE (survived 2x support threshold)")

        top_rule_payload.append({
            "rank":                   int(rank + 1),
            "antecedentItems":        antecedent_items,
            "consequentItems":        consequent_items,
            "antecedent":             antecedent,
            "consequent":             consequent,
            "support":                float(row["support"]),
            "confidence":             float(row["confidence"]),
            "lift":                   lift_value,
            "leverage":               float(row["leverage"]),
            "conviction": (
                float(conviction)
                if (not pd.isna(conviction) and math.isfinite(float(conviction)))
                else None
            ),
            "score":                  weighted_score,
            "promoCode":              promo_code,
            "promoDiscount":          promo_discount,
            "collectorThemeEligible": bool(row["collectorThemeEligible"]),
            "highlyStable":           highly_stable,
            "ruleSignature":          signature,
        })

    return {
        "name":             iteration_name,
        "range":            {"min_id": min_id, "max_id": max_id},
        "transactionCount": int(total_transactions),
        "rawRowCount":      int(raw_row_count),
        "autoSupport":      float(min_support),
        "stabilitySupport": float(stability_support),
        "topRules":         top_rule_payload,
    }


# ─── MAIN ─────────────────────────────────────────────────────────────────────

def main() -> None:
    print("PokéML Recommender — ML Engine")
    print("=" * 60)

    # Load all transaction data from local file
    print(f"Loading transactions from: {DATA_FILE}")
    all_data = load_transactions()
    print(f"Loaded {len(all_data)} rows.")

    max_transaction_id = get_max_transaction_id(all_data)
    iteration_ranges   = build_iteration_ranges(max_transaction_id)

    iterations: list[dict]      = []
    model_history: dict[str, dict] = {}
    previous_result: dict | None   = None

    # Run analysis for each iteration window
    for idx, (iteration_name, min_id, max_id) in enumerate(iteration_ranges, start=1):
        current_result        = analyze_iteration(all_data, iteration_name, min_id, max_id)
        current_top_sig       = first_top_rule_signature(current_result)
        previous_top_sig      = first_top_rule_signature(previous_result)

        # Drift detection — did the #1 rule change vs. the previous iteration?
        drift_detected = bool(
            previous_top_sig
            and current_top_sig
            and previous_top_sig != current_top_sig
        )
        if drift_detected:
            print("\nALERT: Drift Detected — top bundle changed between iterations!")

        current_result["driftDetected"]            = drift_detected
        current_result["previousTopRuleSignature"] = previous_top_sig
        current_result["currentTopRuleSignature"]  = current_top_sig

        iterations.append(current_result)
        model_history[f"iteration_{idx}"] = {
            "name":             iteration_name,
            "range":            current_result.get("range"),
            "topRules":         current_result.get("topRules", []),
            "topRuleSignature": current_top_sig,
        }
        previous_result = current_result

    # Direct comparison between first and last iteration
    comparison_1_vs_3 = {
        "iteration1TopRule": model_history.get("iteration_1", {}).get("topRuleSignature"),
        "iteration3TopRule": model_history.get("iteration_3", {}).get("topRuleSignature"),
        "topRuleChanged": (
            model_history.get("iteration_1", {}).get("topRuleSignature")
            != model_history.get("iteration_3", {}).get("topRuleSignature")
        ),
    }

    # Assemble final output
    output = {
        "generatedAt":            datetime.now(timezone.utc).isoformat(),
        "source":                 "local.data/transactions.json",
        "iterations":             iterations,
        "modelHistory":           model_history,
        "comparisonIteration1Vs3": comparison_1_vs_3,
    }

    # Write to public/analysis-results.json for the React frontend
    public_dir  = Path(__file__).resolve().parent / "public"
    public_dir.mkdir(parents=True, exist_ok=True)
    output_file = public_dir / "analysis-results.json"
    output_file.write_text(json.dumps(output, indent=2), encoding="utf-8")

    print(f"\n{'=' * 60}")
    print(f"Saved analysis results to: {output_file}")
    print("Run 'npm run dev' and open localhost:5173 to view the dashboard.")


if __name__ == "__main__":
    main()
