import json
import math
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd
from mlxtend.frequent_patterns import association_rules, fpgrowth

# ─────────────────────────────────────────────────────────────────────────────
# PokéML Recommender — ML Engine
#
# Reads:  data/transactions.json   (generated by generate_data.py)
# Writes: public/analysis-results.json  (consumed by the React dashboard)
#
# Pipeline per iteration:
#   1. Filter to transaction window
#   2. Clean rows
#   3. Build boolean basket matrix
#   4. Auto-scale support threshold
#   5. FP-Growth frequent itemset mining
#   6. Derive association rules (lift >= 1.0)
#   7. Weighted composite score
#   8. Canonical direction deduplication (item-support based)
#   9. Collector theme bias (+0.02 ranking nudge)
#  10. Select top 3 rules
#  11. Stability check at 2x support
#  12. Build result payload
# ─────────────────────────────────────────────────────────────────────────────

DATA_FILE = Path(__file__).resolve().parent / "data" / "transactions.json"


# ══════════════════════════════════════════════════════════════════════════════
# DATA LOADING
# ══════════════════════════════════════════════════════════════════════════════

def load_transactions() -> pd.DataFrame:
    """Load all transaction rows from the local JSON file into a DataFrame."""
    if not DATA_FILE.exists():
        raise FileNotFoundError(
            f"Transaction data not found at {DATA_FILE}\n"
            "Run generate_data.py first to create the data file."
        )
    with open(DATA_FILE, encoding="utf-8") as f:
        rows = json.load(f)
    return pd.DataFrame(rows)


def get_max_transaction_id(df: pd.DataFrame) -> int:
    """Return the highest transaction_id in the dataset."""
    if df.empty:
        return 0
    return int(df["transaction_id"].max())


def filter_transactions(df: pd.DataFrame, min_id: int, max_id: int) -> pd.DataFrame:
    """Return only the rows whose transaction_id falls within [min_id, max_id]."""
    return df[
        (df["transaction_id"] >= min_id) & (df["transaction_id"] <= max_id)
    ].copy()


def clean_transactions(df: pd.DataFrame) -> pd.DataFrame:
    """
    Clean and validate transaction rows before mining.

    Steps:
      1. Drop rows with null transaction_id or item_name
      2. Strip leading/trailing whitespace from item_name
      3. Drop exact duplicate rows (same transaction_id + item_name)
      4. Ensure transaction_id is integer typed
      5. Reset index to a clean contiguous range

    Prints a summary of rows removed at each stage.
    """
    original_count = len(df)

    # 1. Drop nulls
    df = df.dropna(subset=["transaction_id", "item_name"])
    after_nulls = len(df)

    # 2. Normalise whitespace
    df["item_name"] = df["item_name"].str.strip()

    # 3. Drop duplicate item rows within the same transaction
    df = df.drop_duplicates(subset=["transaction_id", "item_name"])
    after_dupes = len(df)

    # 4. Enforce integer type
    df["transaction_id"] = df["transaction_id"].astype(int)

    # 5. Clean index
    df = df.reset_index(drop=True)

    nulls_removed = original_count - after_nulls
    dupes_removed = after_nulls - after_dupes
    print(
        f"  [Clean] {original_count} rows in "
        f"| nulls removed: {nulls_removed} "
        f"| duplicates removed: {dupes_removed} "
        f"| {len(df)} rows out"
    )
    return df


# ══════════════════════════════════════════════════════════════════════════════
# ITERATION RANGES
# ══════════════════════════════════════════════════════════════════════════════

def build_iteration_ranges(max_transaction_id: int) -> list:
    """
    Build three cumulative analysis windows covering 25%, 50%, and 100%
    of the total transaction range. All windows start from ID 1 so that
    each iteration is a superset of the previous one.
    """
    if max_transaction_id <= 0:
        return [
            ("Iteration 1: Early Launch Phase", 1, 500),
            ("Iteration 2: Mid-Season Update",  1, 1000),
            ("Iteration 3: Full Holiday Trend", 1, 2000),
        ]

    first_cutoff  = max(1, round(max_transaction_id * 0.25))
    second_cutoff = max(first_cutoff + 1, round(max_transaction_id * 0.50))
    full_cutoff   = max_transaction_id

    return [
        ("Iteration 1: Early Launch Phase", 1, first_cutoff),
        ("Iteration 2: Mid-Season Update",  1, second_cutoff),
        ("Iteration 3: Full Holiday Trend", 1, full_cutoff),
    ]


# ══════════════════════════════════════════════════════════════════════════════
# RULE UTILITIES
# ══════════════════════════════════════════════════════════════════════════════

def to_rule_signature(antecedents, consequents) -> str:
    """
    Create a deterministic directional string for a rule.
    Example: {'Pikachu Hoodie'} => {'Pokedex Notebook'}
             becomes  'Pikachu Hoodie=>Pokedex Notebook'
    Multi-item antecedents are pipe-joined after sorting.
    """
    left  = "|".join(sorted(str(i) for i in antecedents))
    right = "|".join(sorted(str(i) for i in consequents))
    return f"{left}=>{right}"


def to_symmetric_signature(antecedents, consequents) -> str:
    """
    Create a direction-agnostic signature so that A=>B and B=>A hash to
    the same string. Used to identify and remove mirror rule duplicates.
    """
    left  = "|".join(sorted(str(i) for i in antecedents))
    right = "|".join(sorted(str(i) for i in consequents))
    return " <-> ".join(sorted([left, right]))


def is_collector_theme_rule(antecedents, consequents) -> bool:
    """
    Returns True if any item in the rule is TCG / collector merchandise.
    Qualifying keywords: 'card', 'graded', 'elite', 'booster'.
    Matching rules receive a soft +0.02 ranking score nudge.
    """
    all_items = [str(i).lower() for i in list(antecedents) + list(consequents)]
    return any(
        kw in item
        for item in all_items
        for kw in ("card", "graded", "elite", "booster")
    )


def first_top_rule_signature(result) -> str:
    """Extract the directional signature of the #1 rule from an iteration result."""
    if not result:
        return None
    top_rules = result.get("topRules") or []
    if not top_rules:
        return None
    r = top_rules[0]
    return to_rule_signature(
        r.get("antecedentItems", []),
        r.get("consequentItems", []),
    )


# ══════════════════════════════════════════════════════════════════════════════
# CANONICAL DIRECTION DEDUPLICATION
# ══════════════════════════════════════════════════════════════════════════════

def pick_canonical_direction(rules: pd.DataFrame, item_support: dict) -> pd.DataFrame:
    """
    For each mirror pair (A->B and B->A), keep only ONE direction using
    the following priority order:

      1. For simple 1-item -> 1-item rules:
         The item with HIGHER individual support becomes the antecedent.

         Why: The item that appears in more transactions independently is
         more likely to already be in a customer's basket, making it the
         natural cart trigger (antecedent). This creates stable, business-
         meaningful directions that don't randomly flip between runs when
         confidence values are close together.

      2. For multi-item antecedent rules (e.g. A+B -> C):
         Keep whichever direction has the higher composite score.

    This replaces the previous naive approach of sorting by confidence alone,
    which caused arrow directions to flip unpredictably between iterations.
    """
    kept_rows = []
    seen_symmetric = set()

    # Pre-sort by score descending so the highest-scoring version of any
    # multi-item rule is encountered first.
    rules_sorted = rules.sort_values("score", ascending=False).reset_index(drop=True)

    for _, row in rules_sorted.iterrows():
        sym_sig = to_symmetric_signature(row["antecedents"], row["consequents"])

        if sym_sig in seen_symmetric:
            continue  # mirror already handled

        ant_list = list(row["antecedents"])
        con_list = list(row["consequents"])

        # ── Priority 1: 1-to-1 rules → fix direction by item support ──────
        if len(ant_list) == 1 and len(con_list) == 1:
            ant_item = ant_list[0]
            con_item = con_list[0]
            ant_supp = item_support.get(ant_item, 0.0)
            con_supp = item_support.get(con_item, 0.0)

            # Consequent has higher individual support → it should be the trigger.
            # Look for the flipped row in the table.
            if con_supp > ant_supp:
                flipped_mask = (
                    rules_sorted["antecedents"].apply(
                        lambda x: sorted(list(x)) == sorted(con_list)
                    )
                    & rules_sorted["consequents"].apply(
                        lambda x: sorted(list(x)) == sorted(ant_list)
                    )
                )
                flipped = rules_sorted[flipped_mask]
                if not flipped.empty:
                    kept_rows.append(flipped.iloc[0])
                    seen_symmetric.add(sym_sig)
                    continue
                # Flipped row absent at this support threshold — keep current

        # ── Priority 2: multi-item or equal-support → keep highest score ──
        kept_rows.append(row)
        seen_symmetric.add(sym_sig)

    if not kept_rows:
        return rules.head(0)

    return pd.DataFrame(kept_rows).reset_index(drop=True)


# ══════════════════════════════════════════════════════════════════════════════
# CORE ITERATION ANALYSIS
# ══════════════════════════════════════════════════════════════════════════════

def _empty_result(
    iteration_name, min_id, max_id,
    total_transactions=0, raw_row_count=0, min_support=0.0
) -> dict:
    """Return a well-formed empty result when no rules can be produced."""
    return {
        "name":             iteration_name,
        "range":            {"min_id": min_id, "max_id": max_id},
        "transactionCount": int(total_transactions),
        "rawRowCount":      int(raw_row_count),
        "autoSupport":      float(min_support),
        "stabilitySupport": float(min(min_support * 2, 1.0)),
        "topRules":         [],
    }


def analyze_iteration(
    all_data: pd.DataFrame,
    iteration_name: str,
    min_id: int,
    max_id: int,
) -> dict:
    """
    Run the 12-step FP-Growth pipeline for one iteration window and return
    a result dictionary consumed by main() and written to analysis-results.json.
    """
    print("\n" + "=" * 60)
    print(f"RUNNING: {iteration_name}")
    print("=" * 60)

    # ── Step 1: Filter to this iteration's transaction window ──────────────
    df = filter_transactions(all_data, min_id, max_id)
    if df.empty:
        print("  No data found for this range.")
        return _empty_result(iteration_name, min_id, max_id)

    # ── Step 2: Clean rows ─────────────────────────────────────────────────
    df = clean_transactions(df)

    # ── Step 3: Build boolean basket matrix ───────────────────────────────
    # Pivot to: rows = transaction_id, columns = item_name, values = True/False
    basket_counts = (
        df.groupby(["transaction_id", "item_name"])["item_name"]
        .count()
        .unstack()
        .fillna(0)
    )
    basket = basket_counts.gt(0)

    total_transactions = len(basket)
    raw_row_count      = len(df)

    # ── Step 4: Auto-scale minimum support threshold ───────────────────────
    # Larger datasets use a tighter threshold because even rare patterns
    # have enough absolute volume to be statistically meaningful.
    if total_transactions <= 500:
        min_support = 0.04
    elif total_transactions <= 1000:
        min_support = 0.02
    else:
        min_support = 0.01

    print(f"  Transactions: {total_transactions} | Auto-Support: {min_support}")

    # ── Step 5: FP-Growth frequent itemset mining ──────────────────────────
    frequent_itemsets = fpgrowth(basket, min_support=min_support, use_colnames=True)
    if frequent_itemsets.empty:
        print("  No frequent itemsets found.")
        return _empty_result(
            iteration_name, min_id, max_id,
            total_transactions, raw_row_count, min_support
        )

    # ── Step 6: Derive association rules (lift >= 1.0 only) ────────────────
    # lift >= 1.0 means items co-occur more than random chance predicts.
    rules = association_rules(
        frequent_itemsets,
        num_itemsets=total_transactions,
        metric="lift",
        min_threshold=1.0,
    )
    if rules.empty:
        print("  No association rules found.")
        return _empty_result(
            iteration_name, min_id, max_id,
            total_transactions, raw_row_count, min_support
        )

    # ── Step 7: Composite weighted score ──────────────────────────────────
    # Support    × 0.4  — how common is this pattern across all transactions?
    # Confidence × 0.4  — how reliably does antecedent predict consequent?
    # Lift       × 0.2  — how much stronger than random chance? (capped at 20%
    #                      weight because lift can inflate for rare pairs)
    rules["score"] = (
          (rules["support"]    * 0.4)
        + (rules["confidence"] * 0.4)
        + (rules["lift"]       * 0.2)
    )

    # ── Step 8: Canonical direction deduplication ──────────────────────────
    # Build item-level individual support from single-item frequent sets.
    item_support = {
        list(row["itemsets"])[0]: float(row["support"])
        for _, row in frequent_itemsets.iterrows()
        if len(row["itemsets"]) == 1
    }
    # Deduplicate mirror rules using item support to fix direction consistently.
    rules = pick_canonical_direction(rules, item_support)

    # ── Step 9: Collector theme bias ──────────────────────────────────────
    # TCG/collector items (booster packs, elite trainer boxes, graded cards)
    # carry higher margins. A soft +0.02 ranking nudge keeps them visible
    # when scores are otherwise close — without changing the displayed score.
    rules["collectorThemeEligible"] = rules.apply(
        lambda row: is_collector_theme_rule(row["antecedents"], row["consequents"]),
        axis=1,
    )
    rules["rankingScore"] = (
        rules["score"]
        + rules["collectorThemeEligible"].astype(float) * 0.02
    )

    # ── Step 10: Select top 3 rules ───────────────────────────────────────
    top_rules = (
        rules
        .sort_values(
            ["rankingScore", "confidence", "support", "lift"],
            ascending=[False, False, False, False],
        )
        .head(3)
        .reset_index(drop=True)
    )

    # ── Step 11: Stability check at 2× support ────────────────────────────
    # Rules surviving double the threshold are "highly stable" — robust enough
    # to be recommended with high confidence even in noisier data.
    stability_support = min(min_support * 2, 1.0)
    stable_rule_signatures = set()

    stable_itemsets = fpgrowth(basket, min_support=stability_support, use_colnames=True)
    if not stable_itemsets.empty:
        stable_rules_df = association_rules(
            stable_itemsets,
            num_itemsets=total_transactions,
            metric="lift",
            min_threshold=1.0,
        )
        if not stable_rules_df.empty:
            # Apply the same canonical direction logic so signatures match.
            stable_item_support = {
                list(row["itemsets"])[0]: float(row["support"])
                for _, row in stable_itemsets.iterrows()
                if len(row["itemsets"]) == 1
            }
            stable_rules_df = pick_canonical_direction(
                stable_rules_df, stable_item_support
            )
            stable_rule_signatures = {
                to_rule_signature(row["antecedents"], row["consequents"])
                for _, row in stable_rules_df.iterrows()
            }

    # ── Step 12: Build result payload ─────────────────────────────────────
    print("\n  --- TOP RULES ---")
    top_rule_payload = []

    for rank, row in top_rules.iterrows():
        ant_items  = sorted(list(row["antecedents"]))
        con_items  = sorted(list(row["consequents"]))
        antecedent = ", ".join(ant_items)
        consequent = ", ".join(con_items)

        lift_value     = float(row["lift"])
        conviction     = row.get("conviction", float("nan"))
        promo_discount = 20 if lift_value > 1.5 else 10
        con_prefix     = "".join(c for c in consequent.upper() if c.isalnum())[:4]
        promo_code     = f"POKE{con_prefix}{int(round(lift_value * 100))}"
        weighted_score = float(row["score"])
        signature      = to_rule_signature(ant_items, con_items)
        highly_stable  = signature in stable_rule_signatures

        print(f"\n  Rank {rank + 1}: '{antecedent}' -> '{consequent}'")
        print(
            f"    Score={weighted_score:.3f} | "
            f"Supp={row['support']:.3f} | "
            f"Conf={row['confidence']:.3f} | "
            f"Lift={lift_value:.3f} | "
            f"Lev={row['leverage']:.3f}"
        )
        print(
            f"    Stable={highly_stable} | "
            f"TCG={bool(row['collectorThemeEligible'])} | "
            f"Promo={promo_code} | Discount={promo_discount}%"
        )

        top_rule_payload.append({
            "rank":                   int(rank + 1),
            "antecedentItems":        ant_items,
            "consequentItems":        con_items,
            "antecedent":             antecedent,
            "consequent":             consequent,
            "support":                float(row["support"]),
            "confidence":             float(row["confidence"]),
            "lift":                   lift_value,
            "leverage":               float(row["leverage"]),
            "conviction": (
                float(conviction)
                if not pd.isna(conviction) and math.isfinite(float(conviction))
                else None
            ),
            "score":                  weighted_score,
            "promoCode":              promo_code,
            "promoDiscount":          promo_discount,
            "collectorThemeEligible": bool(row["collectorThemeEligible"]),
            "highlyStable":           highly_stable,
            "ruleSignature":          signature,
        })

    return {
        "name":             iteration_name,
        "range":            {"min_id": min_id, "max_id": max_id},
        "transactionCount": int(total_transactions),
        "rawRowCount":      int(raw_row_count),
        "autoSupport":      float(min_support),
        "stabilitySupport": float(stability_support),
        "topRules":         top_rule_payload,
    }


# ══════════════════════════════════════════════════════════════════════════════
# MAIN
# ══════════════════════════════════════════════════════════════════════════════

def main() -> None:
    print("PokéML Recommender — ML Engine")
    print("=" * 60)
    print(f"Loading transactions from: {DATA_FILE}")

    all_data = load_transactions()
    print(f"Loaded {len(all_data)} rows.\n")

    max_transaction_id = get_max_transaction_id(all_data)
    iteration_ranges   = build_iteration_ranges(max_transaction_id)

    iterations      = []
    model_history   = {}
    previous_result = None

    for idx, (iteration_name, min_id, max_id) in enumerate(
        iteration_ranges, start=1
    ):
        current_result   = analyze_iteration(all_data, iteration_name, min_id, max_id)
        current_top_sig  = first_top_rule_signature(current_result)
        previous_top_sig = first_top_rule_signature(previous_result)

        # Drift detection: did the #1 ranked rule signature change?
        drift_detected = bool(
            previous_top_sig
            and current_top_sig
            and previous_top_sig != current_top_sig
        )
        if drift_detected:
            print(
                f"\n  DRIFT DETECTED between iteration {idx - 1} and {idx}:"
                f"\n    Was : {previous_top_sig}"
                f"\n    Now : {current_top_sig}"
            )

        current_result["driftDetected"]            = drift_detected
        current_result["previousTopRuleSignature"] = previous_top_sig
        current_result["currentTopRuleSignature"]  = current_top_sig

        iterations.append(current_result)
        model_history[f"iteration_{idx}"] = {
            "name":             iteration_name,
            "range":            current_result.get("range"),
            "topRules":         current_result.get("topRules", []),
            "topRuleSignature": current_top_sig,
        }
        previous_result = current_result

    # Summary: did the top rule change between Iteration 1 and Iteration 3?
    sig_1 = model_history.get("iteration_1", {}).get("topRuleSignature")
    sig_3 = model_history.get("iteration_3", {}).get("topRuleSignature")

    output = {
        "generatedAt":             datetime.now(timezone.utc).isoformat(),
        "source":                  "local.data/transactions.json",
        "iterations":              iterations,
        "modelHistory":            model_history,
        "comparisonIteration1Vs3": {
            "iteration1TopRule": sig_1,
            "iteration3TopRule": sig_3,
            "topRuleChanged":    sig_1 != sig_3,
        },
    }

    public_dir  = Path(__file__).resolve().parent / "public"
    public_dir.mkdir(parents=True, exist_ok=True)
    output_file = public_dir / "analysis-results.json"
    output_file.write_text(json.dumps(output, indent=2), encoding="utf-8")

    print(f"\n{'=' * 60}")
    print(f"Results saved to: {output_file}")
    print(f"Iteration 1 top rule : {sig_1}")
    print(f"Iteration 3 top rule : {sig_3}")
    print(f"Top rule changed     : {sig_1 != sig_3}")
    print("\nRun 'npm run dev' and open localhost:5173 to view the dashboard.")


if __name__ == "__main__":
    main()